[global]
disableWidgetStateDuplicationWarning = true

[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#003f72"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#31333F"
font="sans serif"

[client]
toolbarMode = "minimal"